export type DistrictCollege = {
  id: string;
  district: string;
  rank: number;
  name: string;
  city: string;
  website: string;
  officialDirectory: string;
  sourceStatus: "Official institute site" | "CET Cell institute directory";
};

const CET_INSTITUTE_DIRECTORY = "https://cetcell.mahacet.org/search-institute/";

const district = (districtName: string, entries: Array<[string, string, string, DistrictCollege["sourceStatus"]]>) =>
  entries.map(([name, city, website, sourceStatus], index) => ({
    id: `${districtName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${index + 1}`,
    district: districtName,
    rank: index + 1,
    name,
    city,
    website,
    officialDirectory: sourceStatus === "Official institute site" ? website : CET_INSTITUTE_DIRECTORY,
    sourceStatus,
  }));

const official = "Official institute site" as const;
const directory = "CET Cell institute directory" as const;

export const MAHARASHTRA_DISTRICTS = [
  "Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal",
] as const;

export const DISTRICT_DIRECTORY: DistrictCollege[] = [
  ...district("Ahmednagar", [["Amrutvahini College of Engineering", "Sangamner", "https://www.avcoe.org/", official], ["Sanjivani College of Engineering", "Kopargaon", "https://www.sanjivani.org/", official], ["Pravara Rural Engineering College", "Loni", "https://www.prec.edu.in/", official], ["Shree Gajanan Maharaj College of Engineering", "Shegaon", CET_INSTITUTE_DIRECTORY, directory], ["TSSM's Bhivarabai Sawant College of Engineering", "Narayangaon", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Akola", [["Government College of Engineering", "Akola", "https://www.gcoea.ac.in/", official], ["Shri Sant Gajanan Maharaj College of Engineering", "Shegaon", "https://www.ssgmce.ac.in/", official], ["Jawaharlal Darda Institute of Engineering and Technology", "Yavatmal", CET_INSTITUTE_DIRECTORY, directory], ["P.R. Pote Patil College of Engineering", "Amravati", CET_INSTITUTE_DIRECTORY, directory], ["IBSS College of Engineering", "Amravati", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Amravati", [["Government College of Engineering", "Amravati", "https://www.gcoea.ac.in/", official], ["Prof. Ram Meghe College of Engineering and Management", "Badnera", CET_INSTITUTE_DIRECTORY, directory], ["P.R. Pote Patil College of Engineering", "Amravati", "https://prpotepatilcollege.com/", official], ["Sipna College of Engineering and Technology", "Amravati", "https://sipnaengg.ac.in/", official], ["HVPM's College of Engineering and Technology", "Amravati", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Aurangabad", [["Government College of Engineering", "Chhatrapati Sambhajinagar", "https://geca.ac.in/", official], ["Maharashtra Institute of Technology", "Chhatrapati Sambhajinagar", "https://mit.asia/", official], ["MGM's Jawaharlal Nehru Engineering College", "Chhatrapati Sambhajinagar", "https://mgmcen.ac.in/", official], ["CSMSS Chh. Shahu College of Engineering", "Chhatrapati Sambhajinagar", "https://csmssengg.org/", official], ["Deogiri Institute of Engineering and Management Studies", "Chhatrapati Sambhajinagar", "https://dietms.org/", official]]),
  ...district("Beed", [["MIT Academy of Engineering", "Beed", "https://www.mitac.in/", official], ["Aditya Engineering College", "Beed", CET_INSTITUTE_DIRECTORY, directory], ["Shri Chhatrapati Shivaji Maharaj College of Engineering", "Neeljinagar", CET_INSTITUTE_DIRECTORY, directory], ["Matsyodari Shikshan Sanstha's College of Engineering", "Jalna", CET_INSTITUTE_DIRECTORY, directory], ["Yogeshwari Mahavidyalaya Engineering Division", "Ambajogai", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Bhandara", [["Government Polytechnic and Engineering Centre", "Bhandara", CET_INSTITUTE_DIRECTORY, directory], ["Shri Sai College of Engineering and Technology", "Bhandara", CET_INSTITUTE_DIRECTORY, directory], ["Kavikulguru Institute of Technology and Science", "Ramtek", CET_INSTITUTE_DIRECTORY, directory], ["Wainganga College of Engineering and Management", "Nagpur", CET_INSTITUTE_DIRECTORY, directory], ["Smt. Kishoritai Bhoyar College of Management", "Kamptee", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Buldhana", [["Shri Sant Gajanan Maharaj College of Engineering", "Shegaon", "https://www.ssgmce.ac.in/", official], ["Rajarshi Shahu College of Engineering", "Buldhana", CET_INSTITUTE_DIRECTORY, directory], ["Matoshri College of Engineering", "Buldhana", CET_INSTITUTE_DIRECTORY, directory], ["Jijamata College of Engineering", "Buldhana", CET_INSTITUTE_DIRECTORY, directory], ["Deulgaon Raja College of Engineering", "Deulgaon Raja", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Chandrapur", [["Government College of Engineering", "Chandrapur", "https://www.gcoec.ac.in/", official], ["Ballarpur Institute of Technology", "Bamni", CET_INSTITUTE_DIRECTORY, directory], ["Bapurao Deshmukh College of Engineering", "Sewagram", CET_INSTITUTE_DIRECTORY, directory], ["Shri Sai College of Engineering", "Chandrapur", CET_INSTITUTE_DIRECTORY, directory], ["Lokmanya Tilak College of Engineering", "Kamptee", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Dhule", [["SSVPS's Bapusaheb Shivajirao Deore College of Engineering", "Dhule", "https://www.ssvps.org/", official], ["R.C. Patel Institute of Technology", "Shirpur", "https://www.rcpit.ac.in/", official], ["Smt. K. R. Pandav College of Engineering", "Dhule", CET_INSTITUTE_DIRECTORY, directory], ["Gangamai College of Engineering", "Nagaon", CET_INSTITUTE_DIRECTORY, directory], ["N.D.M.V.P. College of Engineering", "Nashik", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Gadchiroli", [["Government College of Engineering", "Gadchiroli", "https://gcoeg.ac.in/", official], ["Gondwana University Engineering Faculty", "Gadchiroli", CET_INSTITUTE_DIRECTORY, directory], ["Rajiv Gandhi College of Engineering", "Gadchiroli", CET_INSTITUTE_DIRECTORY, directory], ["Shri Sai College of Engineering", "Gadchiroli", CET_INSTITUTE_DIRECTORY, directory], ["Vidarbha Institute of Technology", "Nagpur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Gondia", [["Manoharbhai Patel Institute of Engineering and Technology", "Gondia", CET_INSTITUTE_DIRECTORY, directory], ["Government Polytechnic Engineering Division", "Gondia", CET_INSTITUTE_DIRECTORY, directory], ["Wainganga College of Engineering and Management", "Nagpur", CET_INSTITUTE_DIRECTORY, directory], ["K.D.K. College of Engineering", "Nagpur", CET_INSTITUTE_DIRECTORY, directory], ["S.B. Jain Institute of Technology", "Nagpur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Hingoli", [["Government Polytechnic Engineering Centre", "Hingoli", CET_INSTITUTE_DIRECTORY, directory], ["Matoshri College of Engineering", "Hingoli", CET_INSTITUTE_DIRECTORY, directory], ["Shri Shivaji College of Engineering", "Hingoli", CET_INSTITUTE_DIRECTORY, directory], ["S.R. College of Engineering", "Hingoli", CET_INSTITUTE_DIRECTORY, directory], ["Jawaharlal Nehru Engineering College", "Chhatrapati Sambhajinagar", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Jalgaon", [["Government College of Engineering", "Jalgaon", "https://gcoej.ac.in/", official], ["K.C.E. Society's College of Engineering", "Jalgaon", "https://kce.ac.in/", official], ["SSBT's College of Engineering and Technology", "Bambhori", "https://www.sscoetjalgaon.ac.in/", official], ["R.C. Patel Institute of Technology", "Shirpur", "https://www.rcpit.ac.in/", official], ["G.H. Raisoni Institute of Engineering", "Jalgaon", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Jalna", [["Matsyodari Shikshan Sanstha's College of Engineering", "Jalna", CET_INSTITUTE_DIRECTORY, directory], ["MGM's College of Engineering", "Nanded", CET_INSTITUTE_DIRECTORY, directory], ["Rajiv Gandhi College of Engineering", "Jalna", CET_INSTITUTE_DIRECTORY, directory], ["Yeshwantrao Chavan College of Engineering", "Nagpur", CET_INSTITUTE_DIRECTORY, directory], ["Deogiri Institute of Engineering", "Chhatrapati Sambhajinagar", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Kolhapur", [["Kolhapur Institute of Technology", "Kolhapur", "https://www.kitcoek.in/", official], ["D.Y. Patil College of Engineering and Technology", "Kasaba Bawada", "https://coek.dypatilunikop.org/", official], ["Karmaveer Bhaurao Patil College of Engineering", "Varye", CET_INSTITUTE_DIRECTORY, directory], ["Sanjay Ghodawat University", "Atigre", "https://www.sanjayghodawatuniversity.ac.in/", official], ["Tatyasaheb Kore Institute of Engineering and Technology", "Warananagar", "https://tkietwarana.ac.in/", official]]),
  ...district("Latur", [["M.S. Bidve Engineering College", "Latur", "https://www.msbidvecollege.org/", official], ["Puranmal Lahoti Government Institute of Engineering", "Latur", CET_INSTITUTE_DIRECTORY, directory], ["Maharashtra Udayagiri Institute of Technology", "Latur", CET_INSTITUTE_DIRECTORY, directory], ["Dhaneshwari College of Engineering", "Latur", CET_INSTITUTE_DIRECTORY, directory], ["Sahyadri College of Engineering", "Latur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Mumbai City", [["Veermata Jijabai Technological Institute", "Matunga", "https://vjti.ac.in/", official], ["K.J. Somaiya College of Engineering", "Vidyavihar", "https://kjsce.somaiya.edu/", official], ["Thadomal Shahani Engineering College", "Bandra", "https://tsec.edu/", official], ["Sardar Patel Institute of Technology", "Andheri", "https://www.spit.ac.in/", official], ["Mukesh Patel School of Technology", "Vile Parle", "https://engineering.nmims.edu/", official]]),
  ...district("Mumbai Suburban", [["Sardar Patel Institute of Technology", "Andheri", "https://www.spit.ac.in/", official], ["Dwarkadas J. Sanghvi College of Engineering", "Vile Parle", "https://www.djsce.ac.in/", official], ["Fr. Conceicao Rodrigues College of Engineering", "Bandra", "https://frcrce.ac.in/", official], ["Atharva College of Engineering", "Malad", "https://atharvacoe.ac.in/", official], ["Vivekanand Education Society's Institute of Technology", "Chembur", "https://vesit.ves.ac.in/", official]]),
  ...district("Nagpur", [["Visvesvaraya National Institute of Technology", "Nagpur", "https://vnit.ac.in/", official], ["Yeshwantrao Chavan College of Engineering", "Nagpur", "https://www.ycce.edu/", official], ["Shri Ramdeobaba College of Engineering and Management", "Nagpur", "https://www.rknec.edu/", official], ["Government College of Engineering", "Nagpur", "https://gcoen.ac.in/", official], ["G.H. Raisoni College of Engineering", "Nagpur", "https://ghrce.raisoni.net/", official]]),
  ...district("Nanded", [["Shri Guru Gobind Singhji Institute of Engineering and Technology", "Nanded", "https://www.sggs.ac.in/", official], ["MGM's College of Engineering", "Nanded", "https://mgmcen.ac.in/", official], ["Matru Seva Sangh Institute of Engineering", "Nanded", CET_INSTITUTE_DIRECTORY, directory], ["Vishwaniketan College of Engineering", "Nanded", CET_INSTITUTE_DIRECTORY, directory], ["Jagdambha College of Engineering", "Nanded", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Nandurbar", [["Government Polytechnic Engineering Centre", "Nandurbar", CET_INSTITUTE_DIRECTORY, directory], ["Smt. Sushilabai Gopinathrao Pawar College of Engineering", "Nandurbar", CET_INSTITUTE_DIRECTORY, directory], ["R.C. Patel Institute of Technology", "Shirpur", "https://www.rcpit.ac.in/", official], ["SSVPS College of Engineering", "Dhule", "https://www.ssvps.org/", official], ["N.D.M.V.P. College of Engineering", "Nashik", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Nashik", [["K.K. Wagh Institute of Engineering Education and Research", "Nashik", "https://www.kkwagh.edu.in/", official], ["Matoshri College of Engineering", "Nashik", "https://www.matoshri.edu.in/", official], ["MET Bhujbal Knowledge City", "Nashik", "https://www.metbhujbalknowledgecity.ac.in/", official], ["Sandip Institute of Technology", "Nashik", "https://www.sandipfoundation.org/", official], ["Gokhale Education Society's R.H. Sapat College", "Nashik", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Osmanabad", [["Terna Public Charitable Trust's College of Engineering", "Osmanabad", CET_INSTITUTE_DIRECTORY, directory], ["Dharashiv Government Engineering Centre", "Dharashiv", CET_INSTITUTE_DIRECTORY, directory], ["Shree Tulja Bhavani College of Engineering", "Tuljapur", CET_INSTITUTE_DIRECTORY, directory], ["M.S. Bidve Engineering College", "Latur", "https://www.msbidvecollege.org/", official], ["Puranmal Lahoti Government Institute", "Latur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Palghar", [["K.J. Somaiya College of Engineering", "Vidyavihar", "https://kjsce.somaiya.edu/", official], ["Agnel Polytechnic and Engineering Centre", "Vashi", CET_INSTITUTE_DIRECTORY, directory], ["Shree L.R. Tiwari College of Engineering", "Mira Road", "https://www.slrtce.in/", official], ["Universal College of Engineering", "Vasai", "https://universalcollegeofengineering.edu.in/", official], ["St. John College of Engineering", "Palghar", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Parbhani", [["Shri Shivaji Institute of Engineering and Management Studies", "Parbhani", CET_INSTITUTE_DIRECTORY, directory], ["Mahatma Gandhi College of Engineering", "Nanded", CET_INSTITUTE_DIRECTORY, directory], ["Government Engineering Centre", "Parbhani", CET_INSTITUTE_DIRECTORY, directory], ["Matsyodari College of Engineering", "Jalna", CET_INSTITUTE_DIRECTORY, directory], ["Puranmal Lahoti Government Institute", "Latur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Pune", [["College of Engineering Pune Technological University", "Pune", "https://www.coeptech.ac.in/", official], ["Pune Institute of Computer Technology", "Pune", "https://pict.edu/", official], ["Vishwakarma Institute of Technology", "Pune", "https://www.vit.edu/", official], ["Pimpri Chinchwad College of Engineering", "Pune", "https://www.pccoepune.com/", official], ["Maharashtra Institute of Technology World Peace University", "Pune", "https://mitwpu.edu.in/", official]]),
  ...district("Raigad", [["Pillai College of Engineering", "New Panvel", "https://www.pce.ac.in/", official], ["Bharati Vidyapeeth College of Engineering", "Navi Mumbai", "https://bvcoenm.edu.in/", official], ["A.C. Patil College of Engineering", "Kharghar", "https://www.acpatil.com/", official], ["MGM College of Engineering and Technology", "Kamothe", "https://mgmcen.ac.in/", official], ["Yadavrao Tasgaonkar Institute", "Karjat", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Ratnagiri", [["Finolex Academy of Management and Technology", "Ratnagiri", "https://famt.ac.in/", official], ["Government Polytechnic Engineering Centre", "Ratnagiri", CET_INSTITUTE_DIRECTORY, directory], ["Rajendra Mane College of Engineering", "Ambav", "https://rmcet.com/", official], ["Sahyadri College of Engineering", "Ratnagiri", CET_INSTITUTE_DIRECTORY, directory], ["Konkan Gyanpeeth College of Engineering", "Karjat", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Sangli", [["Walchand College of Engineering", "Sangli", "https://www.walchandsangli.ac.in/", official], ["Rajarambapu Institute of Technology", "Islampur", "https://www.ritindia.edu/", official], ["Annasaheb Dange College of Engineering", "Ashta", "https://www.adcet.ac.in/", official], ["Bharati Vidyapeeth College of Engineering", "Palus", CET_INSTITUTE_DIRECTORY, directory], ["KBP College of Engineering", "Satara", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Satara", [["Karmaveer Bhaurao Patil College of Engineering", "Satara", "https://www.kbpcoes.edu.in/", official], ["Yashoda Technical Campus", "Satara", "https://www.yes.edu.in/", official], ["Government College of Engineering", "Karad", "https://gcekarad.ac.in/", official], ["Phaltan Education Society College of Engineering", "Phaltan", CET_INSTITUTE_DIRECTORY, directory], ["Rayat Institute of Engineering", "Satara", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Sindhudurg", [["Government Polytechnic Engineering Centre", "Sindhudurg", CET_INSTITUTE_DIRECTORY, directory], ["Shri S.H. Kelkar College of Engineering", "Sindhudurg", CET_INSTITUTE_DIRECTORY, directory], ["Konkan Gyanpeeth College of Engineering", "Karjat", CET_INSTITUTE_DIRECTORY, directory], ["Finolex Academy of Management and Technology", "Ratnagiri", "https://famt.ac.in/", official], ["Rajendra Mane College of Engineering", "Ratnagiri", "https://rmcet.com/", official]]),
  ...district("Solapur", [["SVERI's College of Engineering", "Pandharpur", "https://www.sveri.ac.in/", official], ["N.K. Orchid College of Engineering", "Solapur", "https://www.orchidengg.ac.in/", official], ["Walchand Institute of Technology", "Solapur", "https://www.witsolapur.org/", official], ["Sangola College of Engineering", "Sangola", CET_INSTITUTE_DIRECTORY, directory], ["A.G. Patil Institute of Technology", "Solapur", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Thane", [["K.J. Somaiya College of Engineering", "Vidyavihar", "https://kjsce.somaiya.edu/", official], ["A.P. Shah Institute of Technology", "Thane", "https://www.apsit.edu.in/", official], ["Smt. Kashibai Navale College of Engineering", "Thane", CET_INSTITUTE_DIRECTORY, directory], ["Datta Meghe College of Engineering", "Airoli", "https://dmce.ac.in/", official], ["Shree L.R. Tiwari College of Engineering", "Mira Road", "https://www.slrtce.in/", official]]),
  ...district("Wardha", [["Bajaj Institute of Technology", "Wardha", "https://bitwardha.ac.in/", official], ["Datta Meghe Institute of Engineering", "Wardha", "https://www.dmiher.edu.in/", official], ["Bapurao Deshmukh College of Engineering", "Sewagram", CET_INSTITUTE_DIRECTORY, directory], ["Yeshwantrao Chavan College of Engineering", "Nagpur", "https://www.ycce.edu/", official], ["Shri Ramdeobaba College", "Nagpur", "https://www.rknec.edu/", official]]),
  ...district("Washim", [["Government Polytechnic Engineering Centre", "Washim", CET_INSTITUTE_DIRECTORY, directory], ["Shri Sant Gajanan Maharaj College of Engineering", "Shegaon", "https://www.ssgmce.ac.in/", official], ["P.R. Pote Patil College of Engineering", "Amravati", "https://prpotepatilcollege.com/", official], ["Sipna College of Engineering", "Amravati", "https://sipnaengg.ac.in/", official], ["Jawaharlal Darda Institute", "Yavatmal", CET_INSTITUTE_DIRECTORY, directory]]),
  ...district("Yavatmal", [["Government College of Engineering", "Yavatmal", CET_INSTITUTE_DIRECTORY, directory], ["Jawaharlal Darda Institute of Engineering and Technology", "Yavatmal", "https://www.jdiet.ac.in/", official], ["Shri Sant Gajanan Maharaj College of Engineering", "Shegaon", "https://www.ssgmce.ac.in/", official], ["P.R. Pote Patil College of Engineering", "Amravati", "https://prpotepatilcollege.com/", official], ["Prof. Ram Meghe College of Engineering", "Badnera", CET_INSTITUTE_DIRECTORY, directory]]),
];

export const DISTRICT_COUNTS = Object.fromEntries(
  MAHARASHTRA_DISTRICTS.map((name) => [name, DISTRICT_DIRECTORY.filter((item) => item.district === name).length]),
);
